### PR TITLE
chore(app): use @rbarilani/react-simple-inpagenav

### PR DESCRIPTION
**Pull request by rbarilani**
chore(app): use @rbarilani/react-simple-inpagenav

@Nagogus please review.

### CODE REVIEW

**Comment by rbarilani** [comment]
👍

**Comment by rbarilani** [comment]
@Nagogus ping

**Comment by rbarilani** [comment]
@fokusferit This PR it's open since a while now... 
Can you have a look... it's just un update on one dependencies location after we move that library out of zalando OSS space. Thx in advance.

**Comment by Nagogus** [comment]
👍

**Comment by rbarilani** [comment]
👍

**Pull request merged**
